#!/bin/sh
if [ "${SKIP_HEALTHCHECK}" != "true" ]; then
  DEFAULT_PATTERN="[0-4][0-9][0-9]"
  DEFAULT_URI="http://127.0.0.1:${PORT}"
  PATTERN="${2:-${DEFAULT_PATTERN}}"
  URI=${1:-${DEFAULT_URI}}
  (wget --server-response --spider --quiet "${URI}" 2>&1 | awk 'NR==1{print $2}' | grep -q -e "${PATTERN}") || exit 1
fi
